const actionsTypes = {
	FETCH_START: "FETCH_START",
	FETCH_RECENT_SUCCESS: "FETCH_RECENT_SUCCESS",
	FETCH_ERROR: "FETCH_ERROR",
	FETCH_BY_ID_SUCCESS: "FETCH_BY_ID_SUCCESS",
};

export default actionsTypes;
